// Code generated by "stringer -type TrackCode"; DO NOT EDIT.

package enrich

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UpMainFast-1100]
	_ = x[UpSlow-1200]
	_ = x[UpGoods-1300]
	_ = x[UpSingle-1400]
	_ = x[UpLoop-1500]
	_ = x[UpTerminal-1600]
	_ = x[UpCrossover-1700]
	_ = x[UpOtherOrEngine-1800]
	_ = x[UpSiding-1900]
	_ = x[DownMainFast-2100]
	_ = x[DownSlow-2200]
	_ = x[DownGoods-2300]
	_ = x[DownSingle-2400]
	_ = x[DownLoop-2500]
	_ = x[DownTerminal-2600]
	_ = x[DownCrossover-2700]
	_ = x[DownOtherOrEngine-2800]
	_ = x[DownSiding-2900]
	_ = x[ReversibleOrBiDirectionalMainFast-3100]
	_ = x[ReversibleOrBiDirectionalSlow-3200]
	_ = x[ReversibleOrBiDirectionalGoods-3300]
	_ = x[ReversibleOrBidirectionalSingle-3400]
	_ = x[ReversibleOrBiDirectionalLoop-3500]
	_ = x[ReversibleOrBiDirectionalTerminal-3600]
	_ = x[ReversibleOrBiDirectionalCrossover-3700]
	_ = x[ReversibleOrBiDirectionalOtherOrEngine-3800]
	_ = x[ReversibleOrBiDirectionalSiding-3900]
}

const _TrackCode_name = "UpMainFastUpSlowUpGoodsUpSingleUpLoopUpTerminalUpCrossoverUpOtherOrEngineUpSidingDownMainFastDownSlowDownGoodsDownSingleDownLoopDownTerminalDownCrossoverDownOtherOrEngineDownSidingReversibleOrBiDirectionalMainFastReversibleOrBiDirectionalSlowReversibleOrBiDirectionalGoodsReversibleOrBidirectionalSingleReversibleOrBiDirectionalLoopReversibleOrBiDirectionalTerminalReversibleOrBiDirectionalCrossoverReversibleOrBiDirectionalOtherOrEngineReversibleOrBiDirectionalSiding"

var _TrackCode_map = map[TrackCode]string{
	1100: _TrackCode_name[0:10],
	1200: _TrackCode_name[10:16],
	1300: _TrackCode_name[16:23],
	1400: _TrackCode_name[23:31],
	1500: _TrackCode_name[31:37],
	1600: _TrackCode_name[37:47],
	1700: _TrackCode_name[47:58],
	1800: _TrackCode_name[58:73],
	1900: _TrackCode_name[73:81],
	2100: _TrackCode_name[81:93],
	2200: _TrackCode_name[93:101],
	2300: _TrackCode_name[101:110],
	2400: _TrackCode_name[110:120],
	2500: _TrackCode_name[120:128],
	2600: _TrackCode_name[128:140],
	2700: _TrackCode_name[140:153],
	2800: _TrackCode_name[153:170],
	2900: _TrackCode_name[170:180],
	3100: _TrackCode_name[180:213],
	3200: _TrackCode_name[213:242],
	3300: _TrackCode_name[242:272],
	3400: _TrackCode_name[272:303],
	3500: _TrackCode_name[303:332],
	3600: _TrackCode_name[332:365],
	3700: _TrackCode_name[365:399],
	3800: _TrackCode_name[399:437],
	3900: _TrackCode_name[437:468],
}

func (i TrackCode) String() string {
	if str, ok := _TrackCode_map[i]; ok {
		return str
	}
	return "TrackCode(" + strconv.FormatInt(int64(i), 10) + ")"
}
